import type { OrderItem } from "./order.types";

export const orderDummyData: OrderItem[] = [
    {
        id: "1",
        problems: ["Leaking water", "Faulty AC"],
        status: "completed",
        serviceLocation: {
            latitude: 37.7749,
            longitude: -122.4194,
            address: "123 Main St",
            note: "Near the park",
        },
        serviceDate: new Date("2022-01-01T10:00:00Z"),
        propertyType: "Apartment",
        propertyFloor: "3",
        note: "Please bring extra tools",
        customer: {
            id: "c1",
            fullName: "John Doe",
            phone: "1234567890",
        },
        acUnits: [
            {
                id: 1,
                acTypeName: "Window AC",
                acCapacity: "1.5 ton",
                brand: "LG",
                quantity: 2,
            },
            {
                id: 2,
                acTypeName: "Split AC",
                acCapacity: "2 ton",
                brand: "Samsung",
                quantity: 1,
            },
        ],
        cancellationReason: undefined,
        cancellationNote: undefined,
        cancelledBy: undefined,
        invoiceId: undefined,
        totalUnits: 3,
        createdAt: new Date("2022-01-01T09:00:00Z"),
        updatedAt: new Date("2022-01-01T09:15:00Z"),
    },
    {
        id: "2",
        problems: ["Faulty thermostat"],
        status: "completed",
        serviceLocation: {
            latitude: 37.7748,
            longitude: -122.4195,
            address: "456 Elm St",
            note: "Near the school",
        },
        serviceDate: new Date("2022-01-02T14:00:00Z"),
        propertyType: "House",
        propertyFloor: "2",
        note: "Please bring extra filters",
        customer: {
            id: "c2",
            fullName: "Jane Smith",
            phone: "0987654321",
        },
        acUnits: [
            {
                id: 3,
                acTypeName: "Ductless AC",
                acCapacity: "3 ton",
                brand: "Carrier",
                quantity: 1,
            },
        ],
        cancellationReason: undefined,
        cancellationNote: undefined,
        cancelledBy: undefined,
        invoiceId: undefined,
        totalUnits: 1,
        createdAt: new Date("2022-01-02T13:00:00Z"),
        updatedAt: new Date("2022-01-02T13:15:00Z"),
    },
    {
        id: "2",
        problems: ["Faulty thermostat"],
        status: "completed",
        serviceLocation: {
            latitude: 37.7748,
            longitude: -122.4195,
            address: "456 Elm St",
            note: "Near the school",
        },
        serviceDate: new Date("2022-01-02T14:00:00Z"),
        propertyType: "House",
        propertyFloor: "2",
        note: "Please bring extra filters",
        customer: {
            id: "c2",
            fullName: "Jane Smith",
            phone: "0987654321",
        },
        acUnits: [
            {
                id: 3,
                acTypeName: "Ductless AC",
                acCapacity: "3 ton",
                brand: "Carrier",
                quantity: 1,
            },
        ],
        cancellationReason: undefined,
        cancellationNote: undefined,
        cancelledBy: undefined,
        invoiceId: undefined,
        totalUnits: 1,
        createdAt: new Date("2022-01-02T13:00:00Z"),
        updatedAt: new Date("2022-01-02T13:15:00Z"),
    },
    {
        id: "2",
        problems: ["Faulty thermostat"],
        status: "completed",
        serviceLocation: {
            latitude: 37.7748,
            longitude: -122.4195,
            address: "456 Elm St",
            note: "Near the school",
        },
        serviceDate: new Date("2022-01-02T14:00:00Z"),
        propertyType: "House",
        propertyFloor: "2",
        note: "Please bring extra filters",
        customer: {
            id: "c2",
            fullName: "Jane Smith",
            phone: "0987654321",
        },
        acUnits: [
            {
                id: 3,
                acTypeName: "Ductless AC",
                acCapacity: "3 ton",
                brand: "Carrier",
                quantity: 1,
            },
        ],
        cancellationReason: undefined,
        cancellationNote: undefined,
        cancelledBy: undefined,
        invoiceId: undefined,
        totalUnits: 1,
        createdAt: new Date("2022-01-02T13:00:00Z"),
        updatedAt: new Date("2022-01-02T13:15:00Z"),
    },
    {
        id: "2",
        problems: ["Faulty thermostat"],
        status: "completed",
        serviceLocation: {
            latitude: 37.7748,
            longitude: -122.4195,
            address: "456 Elm St",
            note: "Near the school",
        },
        serviceDate: new Date("2022-01-02T14:00:00Z"),
        propertyType: "House",
        propertyFloor: "2",
        note: "Please bring extra filters",
        customer: {
            id: "c2",
            fullName: "Jane Smith",
            phone: "0987654321",
        },
        acUnits: [
            {
                id: 3,
                acTypeName: "Ductless AC",
                acCapacity: "3 ton",
                brand: "Carrier",
                quantity: 1,
            },
        ],
        cancellationReason: undefined,
        cancellationNote: undefined,
        cancelledBy: undefined,
        invoiceId: undefined,
        totalUnits: 1,
        createdAt: new Date("2022-01-02T13:00:00Z"),
        updatedAt: new Date("2022-01-02T13:15:00Z"),
    },
    {
        id: "2",
        problems: ["Faulty thermostat"],
        status: "completed",
        serviceLocation: {
            latitude: 37.7748,
            longitude: -122.4195,
            address: "456 Elm St",
            note: "Near the school",
        },
        serviceDate: new Date("2022-01-02T14:00:00Z"),
        propertyType: "House",
        propertyFloor: "2",
        note: "Please bring extra filters",
        customer: {
            id: "c2",
            fullName: "Jane Smith",
            phone: "0987654321",
        },
        acUnits: [
            {
                id: 3,
                acTypeName: "Ductless AC",
                acCapacity: "3 ton",
                brand: "Carrier",
                quantity: 1,
            },
        ],
        cancellationReason: undefined,
        cancellationNote: undefined,
        cancelledBy: undefined,
        invoiceId: undefined,
        totalUnits: 1,
        createdAt: new Date("2022-01-02T13:00:00Z"),
        updatedAt: new Date("2022-01-02T13:15:00Z"),
    },
    {
        id: "2",
        problems: ["Faulty thermostat"],
        status: "completed",
        serviceLocation: {
            latitude: 37.7748,
            longitude: -122.4195,
            address: "456 Elm St",
            note: "Near the school",
        },
        serviceDate: new Date("2022-01-02T14:00:00Z"),
        propertyType: "House",
        propertyFloor: "2",
        note: "Please bring extra filters",
        customer: {
            id: "c2",
            fullName: "Jane Smith",
            phone: "0987654321",
        },
        acUnits: [
            {
                id: 3,
                acTypeName: "Ductless AC",
                acCapacity: "3 ton",
                brand: "Carrier",
                quantity: 1,
            },
        ],
        cancellationReason: undefined,
        cancellationNote: undefined,
        cancelledBy: undefined,
        invoiceId: undefined,
        totalUnits: 1,
        createdAt: new Date("2022-01-02T13:00:00Z"),
        updatedAt: new Date("2022-01-02T13:15:00Z"),
    },
    {
        id: "2",
        problems: ["Faulty thermostat"],
        status: "cancelled",
        serviceLocation: {
            latitude: 37.7748,
            longitude: -122.4195,
            address: "456 Elm St",
            note: "Near the school",
        },
        serviceDate: new Date("2022-01-02T14:00:00Z"),
        propertyType: "House",
        propertyFloor: "2",
        note: "Please bring extra filters",
        customer: {
            id: "c2",
            fullName: "Jane Smith",
            phone: "0987654321",
        },
        acUnits: [
            {
                id: 3,
                acTypeName: "Ductless AC",
                acCapacity: "3 ton",
                brand: "Carrier",
                quantity: 1,
            },
        ],
        cancellationReason: undefined,
        cancellationNote: undefined,
        cancelledBy: undefined,
        invoiceId: undefined,
        totalUnits: 1,
        createdAt: new Date("2022-01-02T13:00:00Z"),
        updatedAt: new Date("2022-01-02T13:15:00Z"),
    },
    {
        id: "2",
        problems: ["Faulty thermostat"],
        status: "cancelled",
        serviceLocation: {
            latitude: 37.7748,
            longitude: -122.4195,
            address: "456 Elm St",
            note: "Near the school",
        },
        serviceDate: new Date("2022-01-02T14:00:00Z"),
        propertyType: "House",
        propertyFloor: "2",
        note: "Please bring extra filters",
        customer: {
            id: "c2",
            fullName: "Jane Smith",
            phone: "0987654321",
        },
        acUnits: [
            {
                id: 3,
                acTypeName: "Ductless AC",
                acCapacity: "3 ton",
                brand: "Carrier",
                quantity: 1,
            },
        ],
        cancellationReason: undefined,
        cancellationNote: undefined,
        cancelledBy: undefined,
        invoiceId: undefined,
        totalUnits: 1,
        createdAt: new Date("2022-01-02T13:00:00Z"),
        updatedAt: new Date("2022-01-02T13:15:00Z"),
    },
    {
        id: "2",
        problems: ["Faulty thermostat"],
        status: "cancelled",
        serviceLocation: {
            latitude: 37.7748,
            longitude: -122.4195,
            address: "456 Elm St",
            note: "Near the school",
        },
        serviceDate: new Date("2022-01-02T14:00:00Z"),
        propertyType: "House",
        propertyFloor: "2",
        note: "Please bring extra filters",
        customer: {
            id: "c2",
            fullName: "Jane Smith",
            phone: "0987654321",
        },
        acUnits: [
            {
                id: 3,
                acTypeName: "Ductless AC",
                acCapacity: "3 ton",
                brand: "Carrier",
                quantity: 1,
            },
        ],
        cancellationReason: undefined,
        cancellationNote: undefined,
        cancelledBy: undefined,
        invoiceId: undefined,
        totalUnits: 1,
        createdAt: new Date("2022-01-02T13:00:00Z"),
        updatedAt: new Date("2022-01-02T13:15:00Z"),
    },
];

export type EarningSummary = {
    earningDate: Date;
    earningTotal: number;
    orderTotal: number;
    missedOrderCount: number;
    completedOrderCount: number;
    cancelledOrderCount: number;
    cashPaymentTotal: number;
    digitalPaymentTotal: number;
};
